### ISSUE TITLE
Start quiz url invalid in case of extension enabled

### ISSUE THREAD

**Issue by mat2002** [nmanumr/quizsliver#18] opened 2022-10-10 17:33 UTC
When I click on take quiz it gives an error that you can see in the picture:
![1111](https://user-images.githubusercontent.com/95518949/194922755-51608fff-4e47-4c88-9b00-488f9d40d812.jpg)

And it also gives this error
![SS2](https://user-images.githubusercontent.com/95518949/194922985-d5f45726-a8f7-4009-8479-9026deb3d963.jpg)

**Comment by taimooorr** [comment] 2022-10-11 18:36
what kind of help?
you need portal access?

**Comment by nmanumr** [comment] 2022-10-12 07:26
> what kind of help? you need portal access?

Yup, I don;t have access and I need that to fix this issue

**Comment by mat2002** [comment] 2022-10-12 07:32
Ok, thanks.

**Comment by taimooorr** [comment] 2022-10-12 08:39
please drop your contact or social media handle.

**Comment by muhammadziyad009** [comment] 2022-10-12 14:21
please fix the issue of extension and update the extension to newer version where they cant detect the extension

**Comment by hammadcui20** [comment] 2022-10-12 16:49
If you want to access portal then I will give it to you but kindly fix this issue. Contact me at hammadasmat@gmail.com

**Comment by mat2002** [comment] 2022-10-12 16:55
I am working on it. But there is very less chance of fixing this extension
but I will update as soon as possible.

**Comment by nmanumr** [comment] 2022-10-14 00:21
Hi guys, sorry for the late reply I was bit busy the whole week. Anyways I contacted @hammadcui20 let wait for his reply. Meanwhile let me tell you guys that based on my initial instinct the issue is very much fixable because there are not that many ways an extension can be detected by a website.

You guys can reach out to me at my twitter (@nmanumr) or on discord. Also it would be helpful if someone can send the the dom snapshot of cuonline screen with "start quiz" button and error screen. And by dom snapshot I mean press ctrl+s and send me the html along with the contents folders zipped. Most probably this would be enough to fix this issue.

**Comment by nmanumr** [comment] 2022-10-14 00:22
Sorry @mat2002 i couldn't reach out to you as you email is obscured.

**Comment by mat2002** [comment] 2022-10-14 01:27
Ok brother I will send you.
So you need a Dom screenshot right?

**Comment by hammadcui20** [comment] 2022-10-14 12:43
@nmanumr check your email. I have send you via email.

**Comment by nmanumr** [comment] 2022-10-14 19:19
A newer version with a patch is released please try that out. 
I'm closing this issue now, feel free to open a new issue or provide me with feedback on this discussion: https://github.com/nmanumr/quizsliver/discussions/22.

**Closed by nmanumr** 2022-10-14 19:19 UTC
